### PR TITLE
Fix https://github.com/MonoMod/MonoMod/issues/93

### PR DESCRIPTION
**Pull request by punchready**
This might be a temporary solution, but after 3 months, i will take anything.

### CODE REVIEW

**Comment by CEO-Chair** [comment]
I approve of this commit.

**Comment by hakusaro** [comment]
I also approve this commit

**Review by hakusaro — APPROVED** [review]
lgtm_7

**Comment by CEO-Chair** [comment]
this is a very good change :neckbeard:

**Review by nike4613 — APPROVED** [review]
Note that even with this merged, it may not make it into a release for a while.

**Pull request merged**
